[tools]
awscli = "2"
erlang = "27.3"
terraform = "1"
github-cli = "latest"
elixir = "1.18.3-otp-27"
sops = "3"
jq = "1"
age = "1"
packer = "1"
"cargo:lolcrab" = "latest"
yamllint = "1.36"
task = "latest"
