# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
---
name: Setup Elixir
description: Sets up Elixir, Erlang and all Deps, Including Cache
inputs:
  github-token:
    description: Github Token to use for installing task (secrets.GITHUB_TOKEN should work)
    required: true

  cache-version:
    description: Cache busting mechanism
    required: true
    default: v1

runs:
  using: 'composite'
  steps:
    - name: Setup Task
      uses: arduino/setup-task@v2
      with:
        # prevent rate limits by github: https://github.com/arduino/setup-task#repo-token
        repo-token: ${{ inputs.github-token }}

    - name: Setup runtime deps with mise
      uses: jdx/mise-action@v2

    - name: Cache deps/_build dirs
      uses: actions/cache@v4
      id: cache-deps
      with:
        path: |
          app/deps
          app/_build
        key: ${{ runner.os }}-${{ inputs.cache-version }}-mix-${{ hashFiles('**/app/mix.lock') }}
        restore-keys: ${{ runner.os }}-${{ inputs.cache-version }}-mix-

    - name: Install Hex
      shell: 'bash'
      if: steps.cache-deps.outputs.cache-hit == 'true'
      run: task ci:hex:install

    - name: Get Deps
      shell: 'bash'
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: task ci:deps:get
