# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

# these tasks are not run in CI, so they should all have MIX_ENV=dev
env:
  MIX_ENV: dev

tasks:
  setup:
    desc: Runs mix setup in the app dir
    cmd: mix setup

  deps:get:
    desc: Downloads the Elixir dependencies
    cmd: mix deps.get

  deps:clean:unused:
    desc: Unlocks and cleans unused deps from mix.lock
    cmd: mix deps.clean --unlock --unused
