# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  deps:get:
    desc: Downloads the Elixir dependencies
    cmd: mix deps.get

  deps:clean:unused:
    desc: Unlocks and cleans unused deps from mix.lock
    cmd: mix deps.clean --unlock --unused
