# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# use string key of `on` to avoid false positive from yamllint
'on':
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: task ci:compile

  xref:
    name: Xref cyclical compile deps
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Xref cyclical compile deps
        run: task ci:xref

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: task ci:test

  format:
    name: Format
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: task ci:format:check

  unused-deps:
    name: Check for unused deps
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Elixir
        uses: ./.github/actions/setup-elixir
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: task ci:deps:check:unused

  lint-yaml:
    name: Lint Yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Task
        uses: arduino/setup-task@v2
        with:
          # prevent rate limits by github: https://github.com/arduino/setup-task#repo-token
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup runtime deps with mise
        uses: jdx/mise-action@v2

      - name: Lint
        run: task ci:lint:yaml -- -f github
