# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

on:
  push:
  workflow_dispatch:

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    env:
      MIX_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Task
        uses: arduino/setup-task@v2

      - name: Setup runtime deps with mise
        uses: jdx/mise-action@v2

      - name: Get Deps
        run: task ci:deps:get

      - name: Compile
        run: task ci:compile
